version: '2.4'

services:
  phoos-javalin:
    image: evanwht/phoos-javalin:1.0-SNAPSHOT
    volumes:
      - type: bind
        source: ./config
        target: /config
    container_name: phoos-javalin
    ports:
      - "8080:8080"
    depends_on:
      phoos-db:
        condition: service_healthy
    networks:
      - phoos-network

  phoos-db:
    container_name: phoos-db
    build:
      context: db
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: testing
    networks:
      - phoos-network

networks:
  phoos-network:
    driver: bridge