# Use root/example as user/password credentials
version: '3.1'

services:
  phoos-db:
    container_name: phoos-db
    build:
      context: ./
      dockerfile: maria.Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: testing